@startuml

' Definindo as classes principais
class Usuario {
  +id: int
  +nome: string
  +email: string
  +senha: string
  +status: enum('ativo', 'inativo')
  +herarquia: enum('Cidadão', 'Funcionário', 'Administrador')
  +criarRequisicao(descricao: string, prioridade: enum): Requisicao
  +fazerComentario(requisicao: Requisicao, texto: string): Comentario
  +validarAutenticacaoGoogle(autenticacao: Autenticacao)
  +verificarHierarquia(herarquia: Herarquia)
  +cadastrarUsuarioInterno(usuario: Usuario)

}

class Autenticacao {
    +id: int
    +usuario_id: int
    +tolken_google: string
    +data_autenticacao: date
    +validarTolkenGoogle()
    +gerarTolkenGoogle()
}

class Requisicao {
  +id: int
  +descricao: string
  +dataCriacao: date
  +dataAtualizacao: date
  +usuario: Usuario
  +departamento: Departamento
  +statusProcesso: enum('Encaminhamento', 'Concluído', 'Cancelado')
  +prioridade: enum('Baixa', 'Média', 'Alta')
  +adicionarComentario(comentario: Comentario)
  +anexarArquivo(arquivo: Arquivo)
  +atualizarStatus(status: StatusRequisicao)
}

class Departamento {
  +id: int
  +nome: string
  +descricao: string
  +receberRequisicao(requisicao: Requisicao)
}

class Comentario {
  +id: int
  +texto: string
  +dataCriacao: date
  +usuario: Usuario
  +requisicao: Requisicao
}

class Arquivo {
  +id: int
  +nome: string
  +tipo: string
  +caminho: string
  +requisicao: Requisicao
}

class StatusRequisicao {
  +id: int
  +descricao: string
}

' Enum
enum Herarquia {
    CIDADAO
    FUNCIONARIO
    ADMINISTRADOR
}

enum Status {
    ATIVO
    INATIVO
}

enum Prioridade {
    BAIXA
    MEDIA
    ALTA
}

enum StatusProcesso {
    ENCAMINHAMENTO
    CONCLUIDO
    CANCELADO
}

' Definindo as relações
Usuario "1" -- "0..*" Requisicao : cria
Usuario "1" -- "0..*" Comentario : faz
Usuario "1" -- "1*" Autenticacao : faz
Requisicao "1" -- "0..*" Comentario : possui
Requisicao "1" -- "0..*" Arquivo : possui
Requisicao "1" -- "1" StatusRequisicao : tem
Requisicao "0..*" -- "1" Departamento : recebe
Departamento "1" -- "0..*" Requisicao : recebe

@enduml
