@startuml

' Definindo as classes principais
class Usuario {
  +id: int
  +nome: string
  +email: string
  +status: bool
  +token_google: string
  +hierarquia: enum('Cidadão', 'Funcionário', 'Administrador')
  +criarRequisicao(descricao: string, prioridade: enum): Requisicao
  +fazerComentario(requisicao: Requisicao, texto: string): Comentario
  +validarAutenticacaoGoogle(autenticacao: Autenticacao)
  +verificarHierarquia(hierarquia: Hierarquia)
  +cadastrarUsuarioInterno(usuario: Usuario)
  +gerarTokenGoogle(token: string)
  +getPrivilegios(): Privilegio[]

}
class Privilegio {
  +id: int
  +nome: string
  +descricao: string
  +role: string
}

class Requisicao {
  +id: int
  +descricao: string
  +dataCriacao: date
  +dataAtualizacao: date
  +usuario: Usuario
  +departamento: Departamento
  +statusProcesso: enum('Analisando', 'Concluído', 'Cancelado')
  +prioridade: enum('Baixa', 'Média', 'Alta')
  +adicionarComentario(comentario: Comentario)
  +anexarArquivo(arquivo: Arquivo)
  +atualizarStatus(status: StatusRequisicao)
}

class Departamento {
  +id: int
  +nome: string
  +descricao: string
  +receberRequisicao(requisicao: Requisicao)
}

class Comentario {
  +id: int
  +texto: string
  +dataCriacao: date
  +usuario: Usuario
  +requisicao: Requisicao
}

class Arquivo {
  +id: int
  +nome: string
  +tipo: string
  +caminho: string
  +requisicao: Requisicao
}



' Enum
enum Hierarquia {
    CIDADAO
    FUNCIONARIO
    ADMINISTRADOR
}


enum Prioridade {
    BAIXA
    MEDIA
    ALTA
}

enum StatusProcesso {
    ANALISANDO
    CONCLUIDO
    CANCELADO
}

' Definindo as relações
Usuario "1" -- "0..*" Requisicao : cria
Usuario "1" -- "0..*" Comentario : faz
Requisicao "1" -- "0..*" Comentario : possui
Requisicao "1" -- "0..*" Arquivo : possui
Requisicao "0..*" -- "1" Departamento : recebe
Usuario "1..*" -- "1..*" Privilegio : tem

@enduml
