@startuml
start
:Administrador acessa o sistema;
if (Cadastrar funcionário)
    :Insere dados necessários\n(conta Google, hierarquia,\nstatus e privilégio);
    :Sistema valida e salva\no cadastro do funcionário;
    stop

:Funcionario acessa o sistema;

if (Cadastrar requisição)
    :Preenche campos obrigatórios\n(descrição, data, usuário,\ndepartamento, prioridade, status);
    :Sistema valida os dados;
    :Requisição é salva\ncom sucesso;
    stop
else if (Atualizar requisição)
    :Seleciona requisição desejada;
    :Edita campos obrigatórios\n(adiciona data e comentário);
    :Sistema valida e salva\nas alterações;
    stop
else if (Comentar requisição)
    :acessa a área pública;
    :Seleciona requisição desejada;
    :Insere comentário na\ncaixa de texto;
    :Sistema valida e salva o\ncomentário vinculado;
    stop
else if (Consultar requisição)
    :acessa a área pública;
    :Insere protocolo no campo de busca;
    if (Protocolo válido?) then (Sim)
        :Sistema exibe status e\ndetalhes da requisição;
        stop
    else (Não)
        :Exibe mensagem de erro\n("Protocolo não encontrado");
        stop
:Cidadão acessa o sistema;
if (Comentar requisição)
    :acessa a área pública;
    :Seleciona requisição desejada;
    :Insere comentário na\ncaixa de texto;
    :Sistema valida e salva o\ncomentário vinculado;
    stop
else if (Consultar requisição)
    :acessa a área pública;
    :Insere protocolo no campo de busca;
    if (Protocolo válido?) then (Sim)
        :Sistema exibe status e\ndetalhes da requisição;
        stop
    else (Não)
        :Exibe mensagem de erro\n("Protocolo não encontrado");
        stop
    endif
else
    :Retorna ao menu inicial;
endif
@enduml
