@startuml

' Definindo as classes principais
class Usuario {
  +id: int
  +nome: string
  +email: string
  +telefone: string
  +endereco: Endereco
  +status: bool
  +token_google: string
  +hierarquia: enum['Cidadão', 'Funcionário', 'Administrador']
  +cadastrarFuncionario(usuario: Usuario)
  +gerarTokenGoogle(token: string)
  +getPrivilegios(): Privilegio[]

}

class Endereco{
  +id: int
  +rua: string
  +numero: string
  +bairro: string
  +cidade: string
  +estado: string
  +cep: string
  +id_usuario: id
}

class Privilegio {
  +id: int
  +nome: string
  +descricao: string
  +role: string

}

class Requisicao {
  +id: int
  +numeroProtocolo: string
  +descricao: string
  +dataCriacao: date
  +dataAtualizacao: date
  +usuario: Usuario
  +departamento: Departamento
  +statusProcesso: enum['Em Andamento','Analisando', 'Concluído', 'Cancelado', 'Aprovado', 'Reprovado']
  +cadastrarRequisicao(descricao: string, prioridade: enum): Requisicao
  +prioridade: enum['Baixa', 'Média', 'Alta']
  +adicionarComentario(comentario: Comentario)
  +anexarArquivo(arquivo: Arquivo)
  +atualizarStatus(status: StatusRequisicao)
}

class Departamento {
  +id: int
  +nome: string
  +descricao: string
  +receberRequisicao(requisicao: Requisicao)
}

class Comentario {
  +id: int
  +texto: string
  +dataCriacao: date
  +usuario: Usuario
  +requisicao: Requisicao
  +comentarRequisição(requisicao: Requisicao, texto: string)
}

class Arquivo {
  +id: int
  +nome: string
  +tipo: string
  +caminho: string
  +requisicao: Requisicao
}

' Definindo as relações
Usuario "1" -- "0..*" Requisicao : tem
Usuario "1" -- "1" Endereco : cria
Usuario "1" -- "0..*" Comentario : faz
Requisicao "1" -- "0..*" Comentario : possui
Requisicao "1" -- "0..*" Arquivo : possui
Requisicao "0..*" -- "1" Departamento : recebe
Usuario "1..*" -- "1..*" Privilegio : tem

@enduml
